baseURL = 'https://main.d1jeg6aki2mj6z.amplifyapp.com/'
languageCode = 'en-us'
title = "Northwestern University Libraries' Digital Scholarship Research Team's CiteGeist"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "https://www.library.northwestern.edu/use-the-libraries/research-teaching/digital-scholarship/"
weight = 2

[[menu.main]]
name = "Team"
url = "/researchers/"
weight = 3

[[menu.main]]
name = "The Cool Zone"
url = "/coauthors/"
weight = 4

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 5

# [[menu.main]]
# name = "Blog"
# url = "/blog/"
# weight = 6
#
# [[menu.main]]
# name = "Contact"
# url = "/contact/"
# weight = 7
